-- CREATE TABLE macanimals (
--     id int NOT NULL AUTO_INCREMENT,
--     title VARCHAR(255),
--     type VARCHAR(255),
--     descript VARCHAR(255),
--     contact VARCHAR(255),
--     img VARCHAR(255),
--     price DECIMAL(40, 2),
--     PRIMARY KEY(id)
-- )

